/**
 * Generates `render.ts`: the catalog without prompt text (descriptions, design guide, examples), for
 * browsers. Parsing and rendering need names, props, types, enums and children; only the system
 * prompt needs the prose, and that is built on the server (`@gistui/react/prompt`).
 * Run `bun run skill` to regenerate; a catalog test fails when render.ts is stale.
 */

import type { ComponentSpec, PropSpec } from "@gistui/core";
import { components, iconNames, themeColors, unions } from "./index";

const strip = (p: PropSpec): PropSpec => {
  const { description: _d, ...rest } = p as PropSpec & { description?: string };
  if (rest.type === "array" && rest.items) return { ...rest, items: strip(rest.items as PropSpec) } as PropSpec;
  return rest as PropSpec;
};

export function renderCatalogSource(): string {
  const lean: ComponentSpec[] = components.map((c) => {
    const { description: _d, ...rest } = c;
    return { ...rest, props: Object.fromEntries(Object.entries(c.props).map(([k, p]) => [k, strip(p)])) };
  });

  // Hoist prop specs used more than once (the icon enum is used by a dozen components).
  const counts = new Map<string, number>();
  for (const c of lean) for (const p of Object.values(c.props)) {
    const j = JSON.stringify(p);
    if (j.length > 40) counts.set(j, (counts.get(j) ?? 0) + 1);
  }
  const shared = [...counts].filter(([, n]) => n > 1).map(([j]) => j);
  const names = new Map(shared.map((j, i) => [j, `p${i}`]));

  const icons = JSON.stringify(iconNames);
  const lit = (j: string) => j.split(icons).join("icons");
  const lines: string[] = [];
  lines.push("// Generated by `bun run skill` from ./index.ts (the catalog without prompt text). Do not edit.");
  lines.push('import { defineLibrary, type ComponentSpec, type Library, type PropSpec } from "@gistui/core";');
  lines.push("");
  lines.push(`export const iconNames: readonly string[] = ${icons};`);
  lines.push("const icons = iconNames;");
  lines.push(`export const themeColors = ${JSON.stringify(themeColors)} as const;`);
  for (const [j, n] of names) lines.push(`const ${n}: PropSpec = ${lit(j)};`);
  lines.push("");
  lines.push("export const components: readonly ComponentSpec[] = [");
  for (const c of lean) {
    const props = Object.entries(c.props)
      .map(([k, p]) => {
        const j = JSON.stringify(p);
        return `${JSON.stringify(k)}: ${names.get(j) ?? lit(j)}`;
      })
      .join(", ");
    const { props: _p, ...rest } = c;
    const head = JSON.stringify(rest).slice(1, -1);
    lines.push(`  { ${head}${head ? ", " : ""}"props": { ${props} } },`);
  }
  lines.push("];");
  lines.push("");
  lines.push(`export const unions: Readonly<Record<string, readonly string[]>> = ${JSON.stringify(unions)};`);
  lines.push("");
  lines.push("export const library: Library = defineLibrary({ components, unions });");
  lines.push("");
  return lines.join("\n");
}
