import { estimateTokens, generatePrompt } from "@gistui/core";
import { examples, guide, library } from "./index";

/** The skill's reference file: the generated system prompt, wrapped for humans and coding agents. */
export function skillReference(): string {
  const prompt = generatePrompt(library, { examples: "one", libraryExamples: examples, libraryGuide: guide }).text;
  return `<!-- Generated by \`bun run skill\` from @gistui/catalog. Do not edit by hand. -->

# GistUI reference

This is the exact text the model receives as its system prompt with the default library
(≈${estimateTokens(prompt).toLocaleString()} tokens). It lists every component, prop, enum and flag, the design guide and the
canonical example. When you write GistUI by hand, follow it exactly.

\`\`\`text
${prompt.trimEnd()}
\`\`\`
`;
}
