/**
 * Tier A: OpenUI's own in-repo token benchmark (thesysdev/openui benchmarks/, 7 scenarios, GPT-5.2
 * outputs). Each UI is committed as OpenUI Lang plus YAML, Vercel JSON-Render (JSONL patches) and
 * Thesys C1 JSON projections of the same tree. This adds:
 *
 * - GistUI, transcoded from the same OpenUI Lang with OpenUI's own schema: statement for statement
 *   (literal) and the way GistUI's prompt asks (idioms). Each output is validated.
 * - Minified C1 JSON: OpenUI compares against pretty-printed JSON; minified is the fair baseline.
 * - Two tokenizers: o200k_base (GPT-5, as OpenUI reports) and cl100k_base.
 *
 * Usage: bun bench/genui/tier-a.ts → bench/results/tier-a.md + tier-a.json (no API key needed).
 */

import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { createRequire } from "node:module";
import { join } from "node:path";
import { parse } from "@gistui/core";
import { kitFromJSONSchema } from "./catalog";
import { GUB, HERE, RESULTS } from "./gub";
import { ALL_IDIOMS, transcode } from "./transcode";

const OUI = join(HERE, "..", ".cache", "openui", "benchmarks");
if (!existsSync(join(OUI, "samples"))) {
  console.error("OpenUI's benchmark folder is missing. Run: sh bench/genui/setup.sh");
  process.exit(1);
}
const { get_encoding } = createRequire(join(GUB, "package.json"))("tiktoken");
const ENC = { o200k: get_encoding("o200k_base"), cl100k: get_encoding("cl100k_base") };
type Enc = keyof typeof ENC;

const SCENARIOS = ["simple-table", "chart-with-data", "contact-form", "dashboard", "pricing-page", "settings-panel", "e-commerce-product"];
const kit = kitFromJSONSchema(JSON.parse(readFileSync(join(OUI, "schema.json"), "utf8")));
const lib = kit.library();
const read = (f: string) => readFileSync(join(OUI, "samples", f), "utf8");

type Fmt = "gistui" | "gistuiLiteral" | "openui" | "yaml" | "vercel" | "c1" | "c1Min";
const FMTS: Fmt[] = ["gistui", "gistuiLiteral", "openui", "yaml", "vercel", "c1", "c1Min"];
const NAMES: Record<Fmt, string> = {
  gistui: "GistUI",
  gistuiLiteral: "GistUI (literal)",
  openui: "OpenUI Lang",
  yaml: "YAML",
  vercel: "Vercel JSON-Render",
  c1: "Thesys C1 JSON",
  c1Min: "C1 JSON, minified",
};

const rows: { scenario: string; tokens: Record<Enc, Record<Fmt, number>>; valid: { gistui: boolean; gistuiLiteral: boolean }; errors: string[] }[] = [];
for (const sc of SCENARIOS) {
  const oui = read(`${sc}.oui`);
  const c1 = read(`${sc}.c1.json`);
  const text: Record<Fmt, string> = {
    openui: oui,
    gistuiLiteral: transcode(oui, {}, kit),
    gistui: transcode(oui, ALL_IDIOMS, kit),
    yaml: read(`${sc}.yaml`),
    vercel: read(`${sc}.vercel.jsonl`),
    c1,
    c1Min: JSON.stringify(JSON.parse(c1)),
  };
  const tokens = Object.fromEntries(
    (Object.keys(ENC) as Enc[]).map((e) => [e, Object.fromEntries(FMTS.map((f) => [f, ENC[e].encode(text[f]).length]))]),
  ) as Record<Enc, Record<Fmt, number>>;
  const check = (s: string) => parse(s, lib).errors.filter((x) => x.severity === "error" && x.code !== "invalid-child");
  const errs = [...check(text.gistui), ...check(text.gistuiLiteral)];
  rows.push({
    scenario: sc,
    tokens,
    valid: { gistui: check(text.gistui).length === 0, gistuiLiteral: check(text.gistuiLiteral).length === 0 },
    errors: errs.map((e) => `${e.code}: ${e.message}`),
  });
  writeFileSync(join(RESULTS, `tier-a-${sc}.gistui`), text.gistui + "\n");
}

mkdirSync(RESULTS, { recursive: true });
writeFileSync(join(RESULTS, "tier-a.json"), JSON.stringify({ date: new Date().toISOString(), commit: "17be496", rows }, null, 1));

const total = (e: Enc, f: Fmt) => rows.reduce((s, r) => s + r.tokens[e][f], 0);
const vs = (a: number, b: number) => `${a <= b ? "−" : "+"}${Math.abs((1 - a / b) * 100).toFixed(1)}%`;
const table = (e: Enc) => `| Scenario | ${FMTS.map((f) => NAMES[f]).join(" | ")} |
|---|${FMTS.map(() => "---:").join("|")}|
${rows.map((r) => `| ${r.scenario} | ${FMTS.map((f) => r.tokens[e][f]).join(" | ")} |`).join("\n")}
| **Total** | ${FMTS.map((f) => `**${total(e, f)}**`).join(" | ")} |
| GistUI vs each | ${FMTS.map((f) => (f === "gistui" ? "" : vs(total(e, "gistui"), total(e, f)))).join(" | ")} |`;

const md = `# Tier A: OpenUI's in-repo token benchmark

[thesysdev/openui \`benchmarks/\`](https://github.com/thesysdev/openui/tree/main/benchmarks) @ \`17be496\`: 7 scenarios generated by GPT-5.2 at temperature 0. The same UI is committed in four formats. GistUI is transcoded from the OpenUI Lang with OpenUI's own \`schema.json\` (\`bench/genui/tier-a.ts\`). "GistUI" is written the way GistUI's prompt asks: small parts inline, pipe tables, plain strings and bare enum values. "Literal" keeps one statement per component. Minified C1 JSON is the fair JSON baseline; OpenUI's README compares against pretty-printed JSON.

Validity: GistUI parses without errors in ${rows.filter((r) => r.valid.gistui).length} of ${rows.length} scenarios (literal: ${rows.filter((r) => r.valid.gistuiLiteral).length} of ${rows.length}).${rows.some((r) => r.errors.length) ? `\n\n${rows.filter((r) => r.errors.length).map((r) => `- ${r.scenario}: ${r.errors.slice(0, 3).join("; ")}`).join("\n")}` : ""}

## o200k_base (GPT-5; what OpenUI reports)

${table("o200k")}

## cl100k_base

${table("cl100k")}

Generated ${new Date().toISOString().slice(0, 10)} by \`bun bench/genui/tier-a.ts\`. GistUI output per scenario: \`bench/results/tier-a-<scenario>.gistui\`.
`;
writeFileSync(join(RESULTS, "tier-a.md"), md);
console.log(md);
for (const e of Object.values(ENC)) e.free();
